Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Definiuje wzorce adresów URL dla blogs"""

from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    #Strona główna
    path('',views.index, name='index'),
    # Strona z postami
    path('posts/', views.posts, name='posts'),
    # Dodawanie nowego postu
    path('new_post/', views.new_post, name='new_post'),
    # Edycja postu
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
"""Definiuje wzroce adresów URL dla aplikacji users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Dołączenie domyślnych adresów URL uwierzytelnienia
    path('', include('django.contrib.auth.urls')),
    # Strona rejestracji
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text':''}
        

blogs/views.py
from typing import ContextManager
from blogs.models import BlogPost
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404


from .models import BlogPost
from .forms import BlogPostForm
# Create your views here.

def index(request):
    """Strona główna dla aplikacji Blog"""
    #posts = BlogPost.objects.order_by('date_added')

    #context = {'posts': posts}
    return render(request, 'blogs/index.html')

def posts(request):
    """Strona główna z postami"""
    posts = BlogPost.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)

@login_required
def new_post(request):
    """Dodaj nowy post"""

    if request.method != 'POST':
        # Nie przekazano żadnych danych, należy utworzyć pusty formularz
        form = BlogPostForm()
    else:
        # Przekazano dane za pomocą żądania POST, należy je przetworzyć
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user

            if new_post.owner != request.user:
                raise Http404
            else:
                new_post.save()
                #form.save()
                return redirect('blogs:posts')
                #return redirect('blogs:index')

    # wyświetlenie pustego formularza
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """Edycja istniejącego posta"""
    post = BlogPost.objects.get(id=post_id)
    
    if post.owner != request.user:
        raise Http404
        
    if request.method != 'POST':
        # Żądanie początkowe, wypełnienie formularza aktualną treścią wpisu
        form = BlogPostForm(instance=post)
    else:
        # Przekazano dane za pomocą żądania POST, należy je przetworzyć
        form = BlogPostForm(data=request.POST, instance=post)
        if form.is_valid():
            form.save()
            #return redirect('blogs:index')
            return redirect('blogs:posts')

    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.forms.widgets import DateTimeBaseInput
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def register(request):
    """Rejestracja nowego użytkownika"""
    if request.method != 'POST':
        # Wyświetlenie pustego formularza rejestracji użytkownika
        form = UserCreationForm()
    else:
        # Przetworzenie wypełnionego formularza
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Zalogowanie użytkownika, a następnie przekierowanie go na stronę główną
            login(request, new_user)
            return redirect('blogs:index')
    
    # WYświetlenie pustego formularza
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang='pl'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'blogs:index'%}">Blog</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span></button>
    
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogs:posts' %}"> Posty</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Witaj, {{user.username}}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Wyloguj</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Rejestruj</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Zaloguj</a>
          </li>
        {% endif %}
      </ul>
    </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %} {% endblock page_header %}
      </div>
      <div>
        {% block content %} {% endblock content%}
      </div>
    
    </main>
  </body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>Edycja wpisu:</p>

  <form action="{% url 'blogs:edit_post' post.id %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button name="submit">Zapisz edycje</button>
  </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

  {% block page_header %}
    <div class="jumbotron">
      <h1 class="display-3">Dodawaj posty i zobacz swoje postępy</h1>

      <p class="lead">Załóż konto, aby rozpocząć korzystanie z aplikacji
        Blog oraz wyświetlić listę poznawanych tematów. Gdy nauczysz się
        czegoś nowego na dany temat, utwórz wpis podsumowujący to, czego
        się nauczyłeś.</p>
      
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
          role="button">Zarejestruj konto &raquo;</a>  
    </div>
  
  {% endblock page_header %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}


{% block content %}
  <p>Dodaj nowy post: </p>

  <form action = "{% url 'blogs:new_post' %}" method='post'>
      {% csrf_token%}
      {{form.as_p}}
      <button name='submit'>Dodaj post</button>
  </form>
{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h1>Posty</h1>
{% endblock page_header %}


{% block content %}
<div class="pb-2 mb-2">
  <a href="{% url 'blogs:new_post'%}">Dodaj nowy post</a>
</div>

  <ul>
      {% for post in posts %}
        <li>
            <div class="card mb-3 pb-2">
                <h4>
            <!--<a href="{% url 'blogs:posts' post.id}">{{post}}</a>-->
            <div class="pb-2 mb-2 border-bottom bg-light">
                {{post}}
                <small>{{post.date_added|date:'d M Y H:i'}}</small>
            </div>
            
                </h4>
                  <a href="{% url 'blogs:edit_post' post.id %}">Edytuj wpis</a>
                  <p>{{post.text}}</p>
            </div>
        </li>
          
      {% empty %}
        <li>Nie ma żadnych posttttow </li>
      {% endfor %}
  </ul>


{% endblock content %}